{% set name = "pymagicc" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 618dadba92e500736d4d844fe3de9ccd095f2b3c2e8b0c07664d1cb0f616dbae

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas-datapackage-reader
    - f90nml
    - PyYAML
    - scmdata >=0.7.5

test:
  imports:
    - pymagicc

  commands:
    - python -c "import pymagicc; assert pymagicc.__version__ == '{{ version }}'"

about:
  home: https://github.com/openclimatedata/pymagicc
  license: BSD-3-Clause AND CC-BY-NC-SA-3.0
  license_family: BSD
  license_file:
      - LICENSE
      - pymagicc/MAGICC6/License_MAGICC6Executable.txt
  summary: Python wrapper for the simple climate model MAGICC
  doc_url: https://pymagicc.readthedocs.io/en/latest/
  dev_url: https://github.com/openscm/pymagicc

extra:
  recipe-maintainers:
    - znicholls
    - rgieseke
